apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-db-secret
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: {{ .Values.vault.refreshInterval | default "1h" }}
  secretStoreRef:
    name: {{ .Values.vault.secretStoreName }}
    kind: SecretStore
  target:
    name: keycloak-db-secret
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: {{ .Values.vault.dbPath }}
        property: username
    - secretKey: password
      remoteRef:
        key: {{ .Values.vault.dbPath }}
        property: password
