apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ .Values.vault.secretStoreName }}
  namespace: {{ .Release.Namespace }}
spec:
  provider:
    vault:
      server: {{ .Values.vault.address }}
      path: {{ .Values.vault.mountPath | default "secret" }}
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: {{ .Values.vault.role }}
          serviceAccountRef:
            name: {{ .Values.vault.secretAccountName }}
